Wrap HTTPS requests into session blocks to see if the TCP connections actually get closed by some earthy miracle. Screw the requests library and urllib3 and whatever depends on it. Stay tuned for the requests-sucks-ass saga.
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rss.moddb.com', port=443): Max retries exceeded with url: /mods/the-last-days/downloads/feed/rss.xml (Caused by SSLError(OSError(24, 'Too many open files')))

> Keep-Alive
> Excellent news — thanks to urllib3, keep-alive is 100% automatic within a session! Any requests that you make within a session will automatically reuse the appropriate connection!

Super excellent news! Many thanks

https://docs.python-requests.org/en/latest/user/advanced/#session-objects

> Sessions can also be used as context managers:
>
> with requests.Session() as s:
>    s.get('https://httpbin.org/cookies/set/sessioncookie/123456789')
>
>This will make sure the session is closed as soon as the with block is exited, even if unhandled exceptions occurred.